# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\tlibs;calc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61lculator.proto\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1d\n\x0cPrimeRequest\x12\r\n\x05limit\x18\x01 \x01(\r\"\x1e\n\rPrimeResponse\x12\r\n\x05prime\x18\x01 \x03(\r\"\x1d\n\x0e\x41verageRequest\x12\x0b\n\x03num\x18\x01 \x01(\x02\"\"\n\x0f\x41verageResponse\x12\x0f\n\x07\x61verage\x18\x01 \x01(\x02\"\x1d\n\x0e\x46indMaxRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x1e\n\x0f\x46indMaxResponse\x12\x0b\n\x03max\x18\x01 \x01(\x05\x32\xde\x01\n\ncalculator\x12)\n\nSumService\x12\x0b.SumRequest\x1a\x0c.SumResponse\"\x00\x12\x31\n\x0cPrimeService\x12\r.PrimeRequest\x1a\x0e.PrimeResponse\"\x00\x30\x01\x12\x37\n\x0e\x41verageService\x12\x0f.AverageRequest\x1a\x10.AverageResponse\"\x00(\x01\x12\x39\n\x0e\x46indMaxService\x12\x0f.FindMaxRequest\x1a\x10.FindMaxResponse\"\x00(\x01\x30\x01\x42\x0bZ\tlibs;calcb\x06proto3'
)




_SUMREQUEST = _descriptor.Descriptor(
  name='SumRequest',
  full_name='SumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SumRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='SumRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_SUMRESPONSE = _descriptor.Descriptor(
  name='SumResponse',
  full_name='SumResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SumResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_PRIMEREQUEST = _descriptor.Descriptor(
  name='PrimeRequest',
  full_name='PrimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='limit', full_name='PrimeRequest.limit', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=116,
)


_PRIMERESPONSE = _descriptor.Descriptor(
  name='PrimeResponse',
  full_name='PrimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prime', full_name='PrimeResponse.prime', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=148,
)


_AVERAGEREQUEST = _descriptor.Descriptor(
  name='AverageRequest',
  full_name='AverageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='AverageRequest.num', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=179,
)


_AVERAGERESPONSE = _descriptor.Descriptor(
  name='AverageResponse',
  full_name='AverageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='average', full_name='AverageResponse.average', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=215,
)


_FINDMAXREQUEST = _descriptor.Descriptor(
  name='FindMaxRequest',
  full_name='FindMaxRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='FindMaxRequest.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=246,
)


_FINDMAXRESPONSE = _descriptor.Descriptor(
  name='FindMaxResponse',
  full_name='FindMaxResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max', full_name='FindMaxResponse.max', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=278,
)

DESCRIPTOR.message_types_by_name['SumRequest'] = _SUMREQUEST
DESCRIPTOR.message_types_by_name['SumResponse'] = _SUMRESPONSE
DESCRIPTOR.message_types_by_name['PrimeRequest'] = _PRIMEREQUEST
DESCRIPTOR.message_types_by_name['PrimeResponse'] = _PRIMERESPONSE
DESCRIPTOR.message_types_by_name['AverageRequest'] = _AVERAGEREQUEST
DESCRIPTOR.message_types_by_name['AverageResponse'] = _AVERAGERESPONSE
DESCRIPTOR.message_types_by_name['FindMaxRequest'] = _FINDMAXREQUEST
DESCRIPTOR.message_types_by_name['FindMaxResponse'] = _FINDMAXRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SumRequest = _reflection.GeneratedProtocolMessageType('SumRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:SumRequest)
  })
_sym_db.RegisterMessage(SumRequest)

SumResponse = _reflection.GeneratedProtocolMessageType('SumResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUMRESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:SumResponse)
  })
_sym_db.RegisterMessage(SumResponse)

PrimeRequest = _reflection.GeneratedProtocolMessageType('PrimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRIMEREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:PrimeRequest)
  })
_sym_db.RegisterMessage(PrimeRequest)

PrimeResponse = _reflection.GeneratedProtocolMessageType('PrimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRIMERESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:PrimeResponse)
  })
_sym_db.RegisterMessage(PrimeResponse)

AverageRequest = _reflection.GeneratedProtocolMessageType('AverageRequest', (_message.Message,), {
  'DESCRIPTOR' : _AVERAGEREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:AverageRequest)
  })
_sym_db.RegisterMessage(AverageRequest)

AverageResponse = _reflection.GeneratedProtocolMessageType('AverageResponse', (_message.Message,), {
  'DESCRIPTOR' : _AVERAGERESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:AverageResponse)
  })
_sym_db.RegisterMessage(AverageResponse)

FindMaxRequest = _reflection.GeneratedProtocolMessageType('FindMaxRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDMAXREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:FindMaxRequest)
  })
_sym_db.RegisterMessage(FindMaxRequest)

FindMaxResponse = _reflection.GeneratedProtocolMessageType('FindMaxResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINDMAXRESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:FindMaxResponse)
  })
_sym_db.RegisterMessage(FindMaxResponse)


DESCRIPTOR._options = None

_CALCULATOR = _descriptor.ServiceDescriptor(
  name='calculator',
  full_name='calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=503,
  methods=[
  _descriptor.MethodDescriptor(
    name='SumService',
    full_name='calculator.SumService',
    index=0,
    containing_service=None,
    input_type=_SUMREQUEST,
    output_type=_SUMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PrimeService',
    full_name='calculator.PrimeService',
    index=1,
    containing_service=None,
    input_type=_PRIMEREQUEST,
    output_type=_PRIMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AverageService',
    full_name='calculator.AverageService',
    index=2,
    containing_service=None,
    input_type=_AVERAGEREQUEST,
    output_type=_AVERAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FindMaxService',
    full_name='calculator.FindMaxService',
    index=3,
    containing_service=None,
    input_type=_FINDMAXREQUEST,
    output_type=_FINDMAXRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
